<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Zoom</name>
   <tag></tag>
   <elementGuidId>36996b55-ee0c-4dd7-8e22-f082457e8a5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@title='Zoom']//span[@class='button-big-logo-image']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@title='Zoom']//span[@class='button-big-logo-image']</value>
   </webElementProperties>
</WebElementEntity>
