<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Speakercard</name>
   <tag></tag>
   <elementGuidId>1a077e9b-1023-400a-b416-e0e8f52bfca3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body/app-root[1]/div[1]/div[1]/ng-component[1]/ng-component[1]/div[1]/section[1]/div[2]/div[1]/div[2]/div[2]/div[1]/mat-card[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body/app-root[1]/div[1]/div[1]/ng-component[1]/ng-component[1]/div[1]/section[1]/div[2]/div[1]/div[2]/div[2]/div[1]/mat-card[1]</value>
   </webElementProperties>
</WebElementEntity>
