<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Errormessage</name>
   <tag></tag>
   <elementGuidId>24d29782-48a9-4e08-9524-a9ada8e51e44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>toast-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>toast-container</value>
   </webElementProperties>
</WebElementEntity>
