<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Areaofinterest</name>
   <tag></tag>
   <elementGuidId>18b688b2-b96e-4518-8903-cb1008b89396</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body[1]/app-root[1]/new-round-table-create[1]/div[2]/div[2]/div[2]/new-round-table-form[1]/form[1]/div[7]/div[2]/div[1]/div[1]/kendo-formfield[1]/div[1]/kendo-multiselect[1]/div[1]/kendo-searchbar[1]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[1]/app-root[1]/new-round-table-create[1]/div[2]/div[2]/div[2]/new-round-table-form[1]/form[1]/div[7]/div[2]/div[1]/div[1]/kendo-formfield[1]/div[1]/kendo-multiselect[1]/div[1]/kendo-searchbar[1]/input[1]</value>
   </webElementProperties>
</WebElementEntity>
