<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verifytext-Suggesttimeslot</name>
   <tag></tag>
   <elementGuidId>36c6e718-1ac1-415d-a1c8-dd4f2cd86c25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//p[@class='grid-timepicker-alternative']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//p[@class='grid-timepicker-alternative']</value>
   </webElementProperties>
</WebElementEntity>
